### ISSUE TITLE
swc-installation-test-2.py fails on python3.2

### ISSUE THREAD

**Issue by prerit2010** [wking/swc-setup-installation-test#14]
```
python3.2 swc-installation-test-2.py
check command line shell (virtual-shell)... pass
check text/code editor (virtual-editor)...  pass
check web browser (virtual-browser)...  pass
check Git (git)...  pass
check Mercurial (hg)... fail
check EasyMercurial...  fail
check make...   pass
check PyPI installer (virtual-pypi-installer)...    pass
check Setuptools (setuptools)...    fail
check Nose (nosetests)...   fail
check Nose Python package (nose)... fail
check py.test...    fail
check pytest Python package (pytest)... fail
check SQLite 3 (sqlite3)... fail
check SQLite Python package (sqlite3-python)... pass
check Python version (python)...    pass
check IPython script (ipython)...   fail
check IPython Python package (IPython)...   Traceback (most recent call last):
  File "swc-installation-test-2.py", line 1042, in <module>
    passed = check(args)
  File "swc-installation-test-2.py", line 272, in check
    version = checker.check()
  File "swc-installation-test-2.py", line 326, in check
    self._check_dependencies()
  File "swc-installation-test-2.py", line 337, in _check_dependencies
    dependency.check()
  File "swc-installation-test-2.py", line 327, in check
    return self._check()
  File "swc-installation-test-2.py", line 369, in _check
    version = self._get_version()
  File "swc-installation-test-2.py", line 699, in _get_version
    package = self._get_package(self.package)
  File "swc-installation-test-2.py", line 704, in _get_package
    return _importlib.import_module(package)
  File "/usr/lib/python3.2/importlib/__init__.py", line 124, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 821, in _gcd_import
    loader.load_module(name)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, *args, **kwargs)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 342, in _load_module
    exec(code_object, module.__dict__)
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 651
    u'\xff\xff\xff\xff'.encode('iso-8859-15')
                      ^
SyntaxError: invalid syntax
```

**Comment by prerit2010** [comment]
@wking I found this issue while running the script on various python versions through Travis-CI

**Comment by prerit2010** [comment]
As answered [here](http://stackoverflow.com/questions/18252804/syntax-error-in-jinja-2-library), it seems like it's an issue of Jinja2 which requires python3.3 at least.  I am not able to import jinja2 on python3.2
